export const CLUSTER_COLOURS: Record<string, string> = {
  'Management': '#E63946',
  'Business & Financial': '#F4A261',
  'Computer & Mathematical': '#2EC4B6',
  'Architecture & Engineering': '#457B9D',
  'Life, Physical & Social Science': '#8338EC',
  'Community & Social Service': '#FF6B6B',
  'Legal': '#6C757D',
  'Education, Training & Library': '#3A86FF',
  'Arts, Design, Entertainment & Media': '#FB5607',
  'Healthcare Practitioners': '#D62828',
  'Healthcare Support': '#EF476F',
  'Protective Services': '#118AB2',
  'Food Preparation & Serving': '#FFD166',
  'Building & Grounds Maintenance': '#06D6A0',
  'Personal Care & Service': '#F72585',
  'Sales': '#4CC9F0',
  'Office & Administrative Support': '#7209B7',
  'Farming, Fishing & Forestry': '#2D6A4F',
  'Construction & Extraction': '#E76F51',
  'Installation, Maintenance & Repair': '#264653',
  'Production': '#A8DADC',
  'Transportation & Material Moving': '#023E8A',
  'Military Specific': '#6B705C',
  'Other': '#ADB5BD'
};